version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - travelbuddy-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    image: discovery-server
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - travelbuddy-network

  user-service:
    image: user-service
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    networks:
      - travelbuddy-network

  booking-service:
    image: booking-service
    build:
      context: ./bookingservice
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      user-service:
        condition: service_started
      discovery-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    networks:
      - travelbuddy-network

  fare-service:
    image: fare-service
    build:
      context: ./fare-service
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    networks:
      - travelbuddy-network

  frontend:
    image: travelbuddy-frontend
    build:
      context: ../travelbuddy-frontend
    ports:
      - "4200:80"
    depends_on:
      - user-service
      - booking-service
      - fare-service
    networks:
      - travelbuddy-network

networks:
  travelbuddy-network:
    driver: bridge

volumes:
  mysql-data:
